from django.urls import path
from . import new_views
from . import views
from .new_views import api_program_upload_document, upload_program_document, api_detailed_schedule, api_detailed_schedule_detail, employee_lookup
from .assessment_views import schedule_table_api, feedback_form
from .idi_views import idi_analysis
from .analysis_view import analysis
from .auth_views import custom_login, custom_register
from .attendance_views import upload_and_save_attendance

app_name = 'dashboard'

urlpatterns = [
    path('', new_views.home, name='dashboard-home'),
    path('accounts/register/', custom_register, name='register'),
    path('accounts/login/', custom_login, name='login'),
    path('upload/', new_views.upload_excel, name='upload_excel'),
    path('sync-onedrive/', new_views.sync_onedrive, name='sync-onedrive'),
    path('uploaded-files/', new_views.uploaded_files, name='uploaded-files'),
    path('delete-file/<str:filename>/', new_views.delete_uploaded_file, name='delete-uploaded-file'),
    path('edit-file/<str:filename>/', new_views.edit_excel, name='edit-excel'),
    path('programs/calendar/', new_views.calendar_programs, name='calendar_programs'),
    path('programs/non-calendar/', new_views.non_calendar_programs, name='non_calendar_programs'),
    path('programs/<int:program_id>/', new_views.program_details, name='program_details'),
    path('programs/<int:program_id>/report/', new_views.generate_report, name='generate_report'),
    path('trainings/<int:training_id>/', new_views.training_details, name='training_details'),
    path('trainings/<int:training_id>/update/', new_views.update_training, name='update_training'),
    path('trainings/<int:training_id>/add-faculty/', new_views.add_faculty, name='add_faculty'),
    path('faculty/<int:faculty_id>/remove/', new_views.remove_faculty, name='remove_faculty'),
    path('training/<int:training_id>/edit/', new_views.edit_training, name='edit_training'),
    path('training/<int:training_id>/delete/', new_views.delete_training, name='delete_training'),
    path('training/<int:training_id>/content/', new_views.update_training_content, name='update_training_content'),
    path('training/<int:training_id>/benefits/', new_views.update_training_benefits, name='update_training_benefits'),
    path('faculty/<int:faculty_id>/edit/', new_views.edit_faculty, name='edit_faculty'),
    path('programs/add/', new_views.add_program, name='add_program'),
    path('programs/all/', new_views.all_programs, name='all_programs'),
    path('programs/<int:program_id>/delete/', new_views.delete_program, name='delete_program'),
    path('trainings/create/', new_views.create_training, name='create_training'),
    path('programs/<int:program_id>/update/', new_views.update_program, name='update_program'),
    path('calendar/', new_views.calendar_view, name='calendar'),
    path('scheduling/', new_views.calendar_view, name='scheduling'),
    path('api/schedules/', new_views.api_schedules, name='api_schedules'),
    path('api/schedules/batch/', new_views.api_schedules_batch, name='api_schedules_batch'),
    path('api/halls/', new_views.api_halls, name='api_halls'),
    path('api/programs/', new_views.api_programs, name='api_programs'),
    path('api/faculty/', new_views.api_faculty, name='api_faculty'),
    path('api/faculty/<int:faculty_id>/', new_views.api_faculty_detail, name='api_faculty_detail'),
    path('api/faculty/<int:faculty_id>/trainings/', new_views.api_faculty_trainings, name='api_faculty_trainings'),
    path('api/trainings/', new_views.api_trainings, name='api_trainings'),
    path('dashboard/schedule_program/<int:program_id>/', new_views.schedule_program_view, name='schedule_program'),
    path('dashboard/update_program_type/<int:program_id>/', new_views.update_program_type, name='update_program_type'),
    path('mor/upload/', new_views.mor_upload, name='mor_upload'),
    path('mor/list/', new_views.mor_list, name='mor_list'),
    path('schedule-trainings/', new_views.schedule_trainings, name='schedule_trainings'),
    path('api/schedules/bulk/', new_views.api_schedules_batch, name='api_schedules_batch'),
    path('api/program-dates/', new_views.api_program_dates_create, name='api_program_dates_create'),
    path('api/program-dates/<int:sched_id>/', new_views.api_program_dates_update, name='api_program_dates_update'),
    path('api/program-dates/<int:sched_id>/', new_views.api_program_dates_delete, name='api_program_dates_delete'),
    path('api/verify-sync/', new_views.api_verify_sync, name='api_verify_sync'),
    # Schedule-specific URLs (more specific patterns first)
    path('api/schedules/<int:schedule_id>/upload-excel/', new_views.api_schedule_upload_excel, name='api_schedule_upload_excel'),
    path('api/schedules/<int:schedule_id>/upload-document/', new_views.api_schedule_upload_document, name='api_schedule_upload_document'),
    path('api/schedules/<int:schedule_id>/update-type/', new_views.api_schedule_update_type, name='api_schedule_update_type'),
    path('api/schedules/<int:schedule_id>/', new_views.api_schedule_detail, name='api_schedule_detail'),
    path('backup-restore/', new_views.backup_restore_view, name='backup_restore'),
    path('backup-restore/create/', new_views.create_backup, name='create_backup'),
    path('backup-restore/restore/', new_views.restore_backup, name='restore_backup'),
    path('backup-restore/delete/', new_views.delete_backup, name='delete_backup'),
    path('api/programs/<int:program_id>/update_type/', new_views.update_program_type, name='update-program-type'),
    path('api/programs/<int:program_id>/upload_document/', api_program_upload_document, name='api_program_upload_document'),
    path('api/programs/<int:program_id>/list_documents/', new_views.api_program_list_documents, name='api_program_list_documents'),
    path('api/programs/<int:program_id>/delete_document/', new_views.api_program_delete_document, name='api_program_delete_document'),
    # Feedback & Assessment URLs
    path('feedback/form/', feedback_form, name='feedback_form'),
    path('feedback/analysis/<int:schedule_id>/', new_views.feedback_analysis, name='feedback_analysis'),
    path('api/feedback/analysis/<int:schedule_id>/', new_views.api_feedback_analysis_data, name='api_feedback_analysis_data'),
    path('assessment/pre/', new_views.pre_assessment, name='pre_assessment'),
    path('assessment/post/', new_views.post_assessment, name='post_assessment'),
    path('assessment/manager-checklist/', new_views.manager_checklist, name='manager_checklist'),
    path('assessment/roi/', new_views.roi_dashboard, name='roi'),
    # IDI Analysis URL
    path('idi/analysis/<int:schedule_id>/', idi_analysis, name='idi_analysis'),
    path('programs/<int:program_id>/upload-doc/', upload_program_document, name='upload_program_document'),
    path('training/<path:training_ids>/analyze-attendance/', new_views.analyze_attendance, name='analyze-attendance'),
    path('api/trainings/<path:training_ids>/upload_attendance/', new_views.api_training_upload_attendance, name='api_training_upload_attendance'),
    path('api/trainings/<path:training_ids>/view_attendance/', new_views.api_training_view_attendance, name='api_training_view_attendance'),
    path('api/trainings/<path:training_ids>/download_attendance/', new_views.api_training_download_attendance, name='api_training_download_attendance'),
    path('api/trainings/<path:training_ids>/delete_attendance/', new_views.api_training_delete_attendance, name='api_training_delete_attendance'),
    path('api/trainings/<path:training_ids>/attendance/status/', new_views.api_training_attendance_status, name='api_training_attendance_status'),
    path('api/trainings/<path:training_ids>/attendance/list/', new_views.api_training_attendance_list, name='api_training_attendance_list'),
    path('api/attendance/report/', new_views.generate_attendance_report, name='generate_attendance_report'),
    path('dashboard/update_training_type/<int:training_id>/', new_views.update_training_type, name='update_training_type'),
    path('api/schedules/training/<int:training_id>/', new_views.get_training_schedule, name='get_training_schedule'),
    path('api/trainings/<int:training_id>/update-type/', new_views.api_update_training_type, name='api_update_training_type'),
    path('api/detailed-schedule/', api_detailed_schedule, name='api_detailed_schedule'),
    path('api/detailed-schedule/<int:pk>/', api_detailed_schedule_detail, name='api_detailed_schedule_detail'),
    path('api/schedule-table/', schedule_table_api, name='schedule_table_api'),
    path('api/schedules/<int:schedule_id>/delete-excel/', new_views.api_schedule_delete_excel, name='api_schedule_delete_excel'),
    path('analysis/<str:category>/<int:schedule_id>/', analysis, name='analysis'),
    path('analysis/pre-improvement/<int:schedule_id>/', new_views.pre_post_improvement_analysis, name='pre_post_improvement_analysis'),
    # New utility URLs
    path('dashboard-data/', new_views.dashboard_data, name='dashboard_data'),
    path('search/', new_views.search, name='search'),
    path('faculty/', new_views.faculty_list, name='faculty_list'),
    path('api/scheduled-trainings-for-trainings/', new_views.api_scheduled_trainings_for_trainings, name='api_scheduled_trainings_for_trainings'),
    path('api/upload_attendance/', upload_and_save_attendance, name='upload_and_save_attendance'),
    path('api/employee_lookup/', employee_lookup, name='employee_lookup'),
] 